backend:
  name: git-gateway
  branch: master
media_folder: "/img"
public_folder: "/img"
collections:
  - name: "blog"
    label: "Posts"
    label_singular: "Post"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "blog.njk",
        }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          pattern: [".{20,66}", "Must have at least 20 and max. 66 characters"],
        }
      - { label: "Teaser", name: "teaser", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Teaser Image", name: "teaserImage", widget: "image" }
      - { label: "Copyright", name: "copyright", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string", default: "date" }
