backend:
  name: git-gateway
  branch: master
media_folder: "/img"
public_folder: "/img"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "blog.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Teaser", name: "teaser", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "teaserImage", widget: "image" }
      - { label: "Copyright", name: "copyright", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string", default: "date" }
